### PR TITLE
Gradio web demo

### PR DESCRIPTION
**Pull request by AK391**
easy to use web ui in gradio for mobilestylegan

### CODE REVIEW

**Comment by bes-dev** [comment]
@AK391 hey, nice demo. However, this repo is for development tools only. There is another repo (https://github.com/bes-dev/random_face) for demo applications. Could you please move this pool request at that repo like https://github.com/bes-dev/random_face/blob/master/random_face/demo.py?

**Comment by AK391** [comment]
@bes-dev Hi sure, I think its more clearer for users to access the project from this repo as it shares the name for the project and also links to the other repo, I can move it though if you think it should be there

**Comment by bes-dev** [comment]
@AK391 yes, I think it will be better to move this demo to the  https://github.com/bes-dev/random_face.
There is link to random_face project in README as refer to production-quality demos. Thanks! :call_me_hand:

**Comment by AK391** [comment]
@bes-dev ok I have opened a PR there https://github.com/bes-dev/random_face/pull/2

**Pull request closed without merging**
